### ISSUE TITLE
Incorrect saving of box class

### ISSUE THREAD

**Issue by jharaldson** [OpenEndedGroup/Field2#82]
This issue cannot be easily reproduced.

There are some cases where Field seems to save the wrong box class in the .field file, example: giving it :boxClass "fieldbox.boxes.Box" instead of :boxClass "fieldipython.FieldIPythonJPY".

The result of this is that the box turns into a default javascript box

**Comment by marcdownie** [comment]
I'm hoping that this is happening when you load, say, a
fieldipython.FieldIPythonJPY box where JPY is not initializing properly.
Field sees this and gives you a vanilla Box (rather than, say, deleting
your code or failing to load altogether).

If this seems plausible, then the real bug is that Field isn't still saving
the custom nature of boxes even when they've failed to init: that is, it
should keep trying on subsequent loads.

**Comment by jharaldson** [comment]
this is definitely the reason, this issue came up after a new pull and build with some missing JPY files

**Comment by marcdownie** [comment]
Good. I know how to fix it, and now we've got a box class that sometimes
doesn't like to start up, time to fix it.

**Comment by marcdownie** [comment]
Fixed b8fc128
